name = "Syndesis"
license = "Apache-2.0"
licenselink = "https://github.com/syndesisio/syndesis-theme/blob/master/LICENSE.md"
description = "A flexible, customizable, open source platform that provides core integration capabilities as a service."
homepage = "https://syndesisio.github.com/syndesis-theme"
tags = []
features = []
min_version = "0.20.6"

[author]
  name = "Syndesis Developers"
  homepage = "https://syndesis.io/"

